### ISSUE TITLE
데이터 수집/분석 업무 배분(강윤정)

### ISSUE THREAD

**Issue by oleomint** [assistbig/group02#5]
1. TO-DO
  - 각자 맡은 파트 별로 범죄와의 상관관계가 유의미할 것이라고 생각되는 가설을 세우고, 
    그에 맞는 공공데이터를 수집하여 "범죄 유형별 발생건수 데이터" 와 동단위 값을 기준으로
    맵핑하여 상관분석 실시

  - 강윤정님: 함께하는 서울통계 > 통계DB > 행정통계 > 동별 통계 23번~44번 항목

2. 참고자료
  - primary key 값 설정(서울시 동단위 / 첨부1. 서울시_구별_동단위.xls)
  - 인구통계데이터(첨부2. 서울시_구별_동단위_인구관련데이터_2014.xls)
  - 부동산관련데이터(첨부3. 서울시_부동산관련데이터.xls)
[셜록.zip](https://github.com/assistbig/group02/files/243420/default.zip)

**Comment by uniskang** [comment]
ddd

**Comment by uniskang** [comment]
[down](https://drive.google.com/open?id=0B59spuxSzOs4QXlfbG1NUXhEelU)

외국인 비율 과 화재발생 수

**Comment by uniskang** [comment]
5.    시사점 및 한계점 / 향후 개선방안  : 

 우리 작업물의 정확 하거나 풍족 하지 않으니, 데이터를 좀 더 얻을 수 있는 (CCTV 설치) 
다양한 속성의 데이터를 얻을 수 있었으면 좋은 리포트가 나왔을 것이다. 

모델링 이 안나온 얘기  :  
서비스 : 
우리의 고콸러티 EDA 리포트 를 만드느냐 가 우리의 목표 였다  
향후 개선 방안 은 : 우리가 개선 할 꺼는 아니고, 

발전된 모습은, 누군가에 
실시간 연동 x 공공 데이타 가 안맞고 (법정)  년도 안맞고 공공 데이타
합쳐지지않고,  
시사점 :  대쉬 보드 
개선 방안 :  알람을 주는 앱 이나, 안심 콜 을 
CCTV  로 이상 징후가 있는 사람의 움직임을 캡쳐 해서  (강남역 7시간 )

**Comment by uniskang** [comment]
5.시사점 및 한계점 / 향후 개선방안  : 

셜록 팀의 목표는 고콸러티 EDA 리포트 를 만들자 였습니다. 
목표 달성을 위한 한계점 과 시사점은 

한계점  : 공공데이터의 한계 절감

정부는 공공데이터의 적극적인 활용을 장려하기 위해 3.0시대를 열고 데이터 오픈 정도를 평가의 한 지표로까지 삼고 있으나,
현실은 정부의 의지만큼 받쳐주지 못하고 있음을 느낄 수 있었습니다.

(1) 최신 데이타 update 부재 
범죄 발생 데이터만 하더라도, 2014년 8월부터 2015년 7월까지의 데이터가 최신으로 되어 있습니다. 
실시간 API연동, 아니면 최소한 월단위 이하로의 정기적인 자료 업데이트가 가능하다면, 
실제로 일반인들에게 좀 더 유의미한 범죄 관련 데이터를 제공해 줄 수 있을것 같은 마음에 아쉬웠습니다.

(2) 불일치,오타등의 오류
공공데이터의 경우에는, 타이틀과 실제 데이터가 다른 경우 혹은 실 데이터를 내려받을 수 없는 경우들이 있었으며,
오표기나 오타 등의 문제, 행정동과 법정동 간 매핑문제 등으로 인해 데이터 전처리에 인시 소요가 컸습니다

(3) 연결고리가 없어 데이터 가치 저하
범죄 발생 장소관련 데이타가 단순 주소 데이타(구/동) 또는 병원/놀이터 등의 장소 개념으로 그 연결 고리를 이을 수 가 없어
버리는 데이타가 되어 아쉬웠습니다. 
예를 들면 강남구의 남녀 공용 화장실 범죄 발생 건수 데이타 화 할 수 있었다면 좋았을 겁니다. 

(4) 결과 수치 데이타 외 동적 데이타 필요 
범죄 발생후 결과 만의 데이타 뿐만 아니라, 그 과정을 파악하여 실질적 범죄 발생의 요인을 추적 할 수 있는 "동적 데이타" ( CCTV 자료 등) 
등이 있었다면 조금더 실질적인 "범죄 발생 요인과 결과" 를 산출 할 수 있지 않았을까 하는 욕심이 있었습니다

시사점 : 

결과값이 보여주는 시사점 

(1) 범죄 관련 정보 제공
구와 동단위 지역을 기반으로, 일반인들이 평소 접하기 어려운 범죄 관련 정보들을 쉽게 확인할 수 있도록 하여, 
구와 동별 범죄 특성 파악 뿐아니라, 내가 거주하는 동네는 안전한 동네인지, 어떤 범죄가 얼마나 발생했는지를 보기 쉽게
확인 가능 합니다

셜록 Project 를 통한 Lesson & Learned

한계점들 을 극복 하면서 다양한 변수들이 만들어내는 
분석과 유추 통한 데이터 분석 경험을 축적하는 이런 과정이 고도화된  EDA를 만드는 과정 들임을 실감하였습니다

(1) 81개의 데이터의 상관관계 유추를 통한 분석 결과값
각각의 범죄들이 어느곳에서 많이 발생하는지, 왜 그럼 특정 지역에서 많이 발생하는지, 어떤 변수들과 상관관계가 있는지 등
데이터를 구성하고 있는 변수들이 만들어 내는 결과값에 대한 다양한 분석과 유추를 통해 데이터 분석의 경험을 축적 였습니다.

(2) 그 결과값과  범죄 관련 media 비교를 통한 검증 하여
범죄관련 언론기사와 실제 저희조에서 구축한 data set 이 얼마나 일치하는지를 검증하는 과정을 통해 데이터 학습 능력 함양하였습니다


향후 개선 방안 : 

고 품질 EDA 리포트 는 완료 하였다고 생각 합니다. 
 
향후, 좀더 발 전 시킬 수 있는 기회가 제공 된다면,   저희 셜록팀은 
 일반 국민 대상으로 맞춤형 알람서비스 등을 개발 하는 것입니다. 

데이터가 좀 더 유의미하다면, 예를 들어 범죄 발생 건수 데이터가 실시간 연동이 가능하다면, 
CCTV 등의 동적데이터를 추가 하고 나아가서, 실시간 데이터로 이상 징후가 있는 사람의 움직임을 캡쳐 한다는 정도의 
 셜록 처럼 범죄가 발생한 요인들에 대해 파악 할 수 있는 데이타 들의 합이 유기적으로 일어 난다면 
일반인이아와서 검색하는 정보제공이 아닌, 고객의 니즈에 따라 제공하는 맞춤형 알람 서비스 등이 가능할 것으로
보이며, 실제 범죄 예방 차원에서 큰 효과가 있을 것으로 판단 됩니다.
